spring.application.name=ballet-api

spring.datasource.url=jdbc:mysql://localhost:3306/ballet_db?serverTimezone=UTC
spring.datasource.username= root
spring.datasource.password=


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.swagger-ui.operationsSorter=method

springdoc.swagger-ui.path = /swagger-iu.html